<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = $this->permissions();
        foreach ($permissions as $permission) {
            $check_permission = Permission::where('name',$permission['name'])->first();
            if (is_null($check_permission)) {
                Permission::create($permission);
            }
            else{
                $check_permission->update($permission);
            }
        }
    }

    private function permissions()
    {
        return [
            array('name' => 'permissions_manage', 'title' => 'Permissions', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'permissions_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 1),
            array('name' => 'permissions_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 1),
            array('name' => 'permissions_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 1),
            array('name' => 'dashboard_manage', 'title' => 'Dashboard', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'dashboard_revenue_by_centre', 'title' => 'Revenue by Centre', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'dashboard_revenue_by_service', 'title' => 'Revenue by Service', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'dashboard_my_revenue_by_centre', 'title' => 'My Performance by Centre', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'dashboard_my_revenue_by_service', 'title' => 'My Performance by Service', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'dashboard_appointment_by_status', 'title' => 'Appointment by Status', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'dashboard_appointment_by_type', 'title' => 'Appointment by Type', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'dashboard_my_appointment_by_status', 'title' => 'My Appointments Performance by Status', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'dashboard_my_appointment_by_type', 'title' => 'My Appointments Performance by Type', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'roles_manage', 'title' => 'Roles', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'roles_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 14),
            array('name' => 'roles_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 14),
            array('name' => 'roles_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 14),
            array('name' => 'roles_destroy_bulk', 'title' => 'Delete Bulk', 'main_group' => 0, 'parent_id' => 14),
            array('name' => 'resource_types_manage', 'title' => 'Resource Types', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'resource_types_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 19),
            array('name' => 'resource_types_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 19),
            array('name' => 'resource_types_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 19),
            array('name' => 'resource_types_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 19),
            array('name' => 'resource_types_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 19),
            array('name' => 'user_types_manage', 'title' => 'User Types', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'user_types_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 25),
            array('name' => 'users_manage', 'title' => 'Users', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'users_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 27),
            array('name' => 'users_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 27),
            array('name' => 'users_change_password', 'title' => 'Change Password', 'main_group' => 0, 'parent_id' => 27),
            array('name' => 'users_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 27),
            array('name' => 'regions_manage', 'title' => 'Regions', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'regions_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 32),
            array('name' => 'regions_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 32),
            array('name' => 'regions_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 32),
            array('name' => 'regions_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 32),
            array('name' => 'regions_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 32),
            array('name' => 'regions_sort', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 32),
            array('name' => 'cities_manage', 'title' => 'Cities', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'cities_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 39),
            array('name' => 'cities_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 39),
            array('name' => 'cities_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 39),
            array('name' => 'cities_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 39),
            array('name' => 'cities_sort', 'title' => 'Sort', 'main_group' => 0, 'parent_id' => 39),
            array('name' => 'services_manage', 'title' => 'Services', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'services_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 46),
            array('name' => 'services_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 46),
            array('name' => 'services_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 46),
            array('name' => 'services_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 46),
            array('name' => 'services_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 46),
            array('name' => 'locations_manage', 'title' => 'Centres', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'locations_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 52),
            array('name' => 'locations_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 52),
            array('name' => 'locations_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 52),
            array('name' => 'locations_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 52),
            array('name' => 'locations_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 52),
            array('name' => 'locations_sort', 'title' => 'Sort', 'main_group' => 0, 'parent_id' => 52),
            array('name' => 'appointment_statuses_manage', 'title' => 'Appointment Statuses', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'appointment_statuses_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 59),
            array('name' => 'appointment_statuses_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 59),
            array('name' => 'appointment_statuses_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 59),
            array('name' => 'appointment_statuses_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 59),
            array('name' => 'appointment_statuses_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 59),
            array('name' => 'appointments_manage', 'title' => 'Appointments', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'appointments_consultancy', 'title' => 'Manage Consultancy', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_services', 'title' => 'Manage Services', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_export', 'title' => 'Export', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_appointment_status', 'title' => 'Update Appointment Status', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_invoice', 'title' => 'Appointment Invoice', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_image_manage', 'title' => 'Images', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_image_upload', 'title' => 'Images Upload', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_image_destroy', 'title' => 'Images Delete', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_measurement_manage', 'title' => 'Measurement', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_measurement_create', 'title' => 'Measurements Create', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_measurement_edit', 'title' => 'Measurements Edit', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'lead_sources_manage', 'title' => 'Lead Sources', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'lead_sources_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 78),
            array('name' => 'lead_sources_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 78),
            array('name' => 'lead_sources_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 78),
            array('name' => 'lead_sources_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 78),
            array('name' => 'lead_sources_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 78),
            array('name' => 'lead_sources_sort', 'title' => 'Sort', 'main_group' => 0, 'parent_id' => 78),
            array('name' => 'lead_statuses_manage', 'title' => 'Lead Statuses', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'lead_statuses_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 85),
            array('name' => 'lead_statuses_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 85),
            array('name' => 'lead_statuses_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 85),
            array('name' => 'lead_statuses_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 85),
            array('name' => 'lead_statuses_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 85),
            array('name' => 'lead_statuses_sort', 'title' => 'Sort', 'main_group' => 0, 'parent_id' => 85),
            array('name' => 'leads_manage', 'title' => 'Leads', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'leads_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 92),
            array('name' => 'leads_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 92),
            array('name' => 'leads_import', 'title' => 'Import', 'main_group' => 0, 'parent_id' => 92),
            array('name' => 'leads_export', 'title' => 'Export', 'main_group' => 0, 'parent_id' => 92),
            array('name' => 'leads_convert', 'title' => 'Convert', 'main_group' => 0, 'parent_id' => 92),
            array('name' => 'leads_lead_status', 'title' => 'Update Lead Status', 'main_group' => 0, 'parent_id' => 92),
            array('name' => 'leads_city', 'title' => 'Update City', 'main_group' => 0, 'parent_id' => 92),
            array('name' => 'leads_junk', 'title' => 'Junk', 'main_group' => 0, 'parent_id' => 92),
            array('name' => 'settings_manage', 'title' => 'Settings', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'settings_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 101),
            array('name' => 'sms_templates_manage', 'title' => 'Sms Templates', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'sms_templates_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 103),
            array('name' => 'sms_templates_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 103),
            array('name' => 'discounts_manage', 'title' => 'Discounts', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'discounts_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 107),
            array('name' => 'discounts_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 107),
            array('name' => 'discounts_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 107),
            array('name' => 'discounts_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 107),
            array('name' => 'discounts_allocate', 'title' => 'Allocate', 'main_group' => 0, 'parent_id' => 107),
            array('name' => 'doctors_manage', 'title' => 'Doctors', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'doctors_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 114),
            array('name' => 'doctors_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 114),
            array('name' => 'doctors_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 114),
            array('name' => 'doctors_change_password', 'title' => 'Change Password', 'main_group' => 0, 'parent_id' => 114),
            array('name' => 'doctors_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 114),
            array('name' => 'doctors_allocate', 'title' => 'Allocate', 'main_group' => 0, 'parent_id' => 114),
            array('name' => 'resources_manage', 'title' => 'Resources', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'resources_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 122),
            array('name' => 'resources_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 122),
            array('name' => 'resources_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 122),
            array('name' => 'resources_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 122),
            array('name' => 'resources_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 122),
            array('name' => 'resourcerotas_manage', 'title' => 'Resource Rotas', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'resourcerotas_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 128),
            array('name' => 'resourcerotas_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 128),
            array('name' => 'resourcerotas_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 128),
            array('name' => 'resourcerotas_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 128),
            array('name' => 'resourcerotas_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 128),
            array('name' => 'resourcerotas_calender', 'title' => 'Calender', 'main_group' => 0, 'parent_id' => 128),
            array('name' => 'payment_modes_manage', 'title' => 'Payment Modes', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'payment_modes_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 135),
            array('name' => 'payment_modes_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 135),
            array('name' => 'payment_modes_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 135),
            array('name' => 'payment_modes_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 135),
            array('name' => 'payment_modes_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 135),
            array('name' => 'payment_modes_sort', 'title' => 'Sort', 'main_group' => 0, 'parent_id' => 135),
            array('name' => 'custom_forms_manage', 'title' => 'Custom Forms', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'custom_forms_create_general', 'title' => 'Create General', 'main_group' => 0, 'parent_id' => 142),
            array('name' => 'custom_forms_create_measurement', 'title' => 'Create Measurement', 'main_group' => 0, 'parent_id' => 142),
            array('name' => 'custom_forms_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 142),
            array('name' => 'custom_forms_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 142),
            array('name' => 'custom_forms_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 142),
            array('name' => 'custom_forms_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 142),
            array('name' => 'custom_forms_preview', 'title' => 'Preview', 'main_group' => 0, 'parent_id' => 142),
            array('name' => 'custom_forms_submit', 'title' => 'Submit', 'main_group' => 0, 'parent_id' => 142),
            array('name' => 'custom_form_feedbacks_manage', 'title' => 'Custom Form Feedbacks', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'custom_form_feedbacks_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 151),
            array('name' => 'custom_form_feedbacks_preview', 'title' => 'Preview', 'main_group' => 0, 'parent_id' => 151),
            array('name' => 'logs_manage', 'title' => 'Logs', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'user_operator_settings_manage', 'title' => 'User Operator Settings', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'user_operator_settings_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 155),
            array('name' => 'plans_manage', 'title' => 'Plans', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'plans_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'plans_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'plans_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'plans_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'plans_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'finances_manage', 'title' => 'Finances', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'finances_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 163),
            array('name' => 'invoices_manage', 'title' => 'Invoices', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'invoices_cancel', 'title' => 'Cancel', 'main_group' => 0, 'parent_id' => 165),
            array('name' => 'refunds_manage', 'title' => 'Refunds', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'refunds_refund', 'title' => 'Refund', 'main_group' => 0, 'parent_id' => 167),
            array('name' => 'patients_manage', 'title' => 'Patients', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'patients_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_appointment_manage', 'title' => 'Appointment Manage', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_customform_manage', 'title' => 'Custom Form Manage', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_customform_create', 'title' => 'Document Create', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_customform_edit', 'title' => 'Document Edit', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_document_manage', 'title' => 'Document Manage', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_document_create', 'title' => 'Document Create', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_document_edit', 'title' => 'Document Edit', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_document_destroy', 'title' => 'Document Destroy', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_manage', 'title' => 'Plan Manage', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_create', 'title' => 'Plan Create', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_inactive', 'title' => 'Plan Inactive', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_active', 'title' => 'Plan Active', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_destroy', 'title' => 'Plan Destroy', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_edit', 'title' => 'Plan Edit', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_finance_manage', 'title' => 'Finance Manage', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_finance_create', 'title' => 'Finance Create', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_invoice_manage', 'title' => 'Invoice Manage', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_invoice_cancel', 'title' => 'Invoice Cancel', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_refund_manage', 'title' => 'Refund Manage', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_refund_refund', 'title' => 'Refund Refund', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'packages_manage', 'title' => 'Packages', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'packages_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 195),
            array('name' => 'packages_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 195),
            array('name' => 'packages_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 195),
            array('name' => 'packages_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 195),
            array('name' => 'packages_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 195),
            array('name' => 'staff_targets_manage', 'title' => 'Staff Targets', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'staff_targets_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 201),
            array('name' => 'staff_targets_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 201),
            array('name' => 'staff_targets_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 201),
            array('name' => 'leads_reports_manage', 'title' => 'Lead Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'leads_reports_general_report', 'title' => 'General Report', 'main_group' => 0, 'parent_id' => 205),
            array('name' => 'leads_reports_summary_report_by_lead_status', 'title' => 'Summary Report By Lead Status', 'main_group' => 0, 'parent_id' => 205),
            array('name' => 'leads_reports_lead_status_percentage', 'title' => 'Lead Status Percentage', 'main_group' => 0, 'parent_id' => 205),
            array('name' => 'appointment_reports_manage', 'title' => 'Appointment Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'appointment_reports_general_report', 'title' => 'General Report', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'appointment_reports_staff_appointment', 'title' => 'Staff Wise Appointment Report', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'appointment_reports_referred_by_staff_appointment', 'title' => 'Staff Wise (red) Appointment Report', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'appointment_reports_empolyee_summary', 'title' => 'Appointment Summary Report', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'appointment_reports_summary_by_service', 'title' => 'Appointments Summary by Service', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'appointment_reports_summary_by_appointment_status', 'title' => 'Appointments Summary by Status', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'appointment_reports_clients_by_appointment_status', 'title' => 'Patient by Appointment Status ( W)', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'operations_reports_manage', 'title' => 'Operation Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'operations_reports_operations_company_health', 'title' => 'Company Health Report', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'operations_reports_Highest_paying_clients', 'title' => 'Highest Paying Clients', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'operations_reports_List_of_refunds_for_a_certain_period_date_based', 'title' => 'List of refunds for a certain period ( ba)', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'operations_reports_List_of_services_that_CAN_be_offered_Complimentary', 'title' => 'List of services that CAN be offered Complimentary', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'operations_reports_List_of_services_that_CAN_not_be_offered_Complimentary', 'title' => 'List of services that CAN NOT be offered Complimentary', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'operations_reports_conversion_report_consultancy', 'title' => 'Conversion Report For Consultancy', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'operations_reports_conversion_report_treatment', 'title' => 'Conversion Report For Treatment', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'operations_reports_dar_report', 'title' => 'DAR Report', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'operations_reports_complimentory_report', 'title' => 'Complimentory Treatment Report', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'operations_reports_dtr_report', 'title' => 'DTR Report', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'centers_reports_manage', 'title' => 'Centre Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'centers_reports_client_with_Completed_treatment', 'title' => 'Clients with completed treatments', 'main_group' => 0, 'parent_id' => 228),
            array('name' => 'centers_reports_client_with_not_Completed_treatment', 'title' => 'Clients with not completed treatments', 'main_group' => 0, 'parent_id' => 228),
            array('name' => 'centers_reports_clients_took_treatments_particular_month', 'title' => 'Clients with treatments in a particular month', 'main_group' => 0, 'parent_id' => 228),
            array('name' => 'centers_reports_clients_with_birthday_days', 'title' => 'Clients with birthday + x days', 'main_group' => 0, 'parent_id' => 228),
            array('name' => 'marketing_reports_manage', 'title' => 'Marketing Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'Hr_reports_manage', 'title' => 'HR Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'Hr_reports_reports_for_calculating_incentives', 'title' => 'Reports For Calculating Incentives', 'main_group' => 0, 'parent_id' => 234),
            array('name' => 'Hr_reports_reports_for_calculating_incentives_detail', 'title' => 'Reports For Calculating Incentives Detail', 'main_group' => 0, 'parent_id' => 234),
            array('name' => 'Hr_reports_revenue_generated_by_operators_application_user', 'title' => 'Revenue Generated By Operators (ication U)', 'main_group' => 0, 'parent_id' => 234),
            array('name' => 'Hr_reports_revenue_generated_by_consultants_practitioner', 'title' => 'Revenue Generated By Consultants (titio)', 'main_group' => 0, 'parent_id' => 234),
            array('name' => 'finance_general_revenue_reports_manage', 'title' => 'Finance General Revenue Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'finance_general_revenue_reports_center_performance_stats_by_revenue_finance', 'title' => 'Center performance stats by Revenue', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_center_performance_stats_by_service_type_finance', 'title' => 'Center performance stats by Service Type', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_daily_employee_stats_summary', 'title' => 'Sale Summary Service Wise', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_daily_employee_stats', 'title' => 'Sale Summary Doctors Wise', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_sales_by_service_category', 'title' => 'Sale Summary Category Wise', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_discount_report', 'title' => 'Discount Report', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_revenue_breakup_reports_manage', 'title' => 'Finance Revenue Breakup Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'finance_ledger_reports_manage', 'title' => 'Finance Ledger Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'finance_ledger_reports_Customer_payment_ledger_all_entries', 'title' => 'Customer Payment Ledger', 'main_group' => 0, 'parent_id' => 248),
            array('name' => 'finance_ledger_reports_customer_treatment_package_ledger', 'title' => 'Customer Treatment Package Ledger', 'main_group' => 0, 'parent_id' => 248),
            array('name' => 'finance_ledger_reports_list_of_advances_as_of_today', 'title' => 'List of Advances as of Today', 'main_group' => 0, 'parent_id' => 248),
            array('name' => 'finance_ledger_reports_list_of_outstanding_as_of_today', 'title' => 'List of Outstanding as of Today', 'main_group' => 0, 'parent_id' => 248),
            array('name' => 'finance_ledger_reports_Summarized_data_of_Discounts_given_to_the_customer', 'title' => 'Summarized Data of Discounts given to the Customer', 'main_group' => 0, 'parent_id' => 248),
            array('name' => 'finance_ledger_reports_List_of_Clients_who_claimed_refunds', 'title' => 'List of Clients Who Claimed Refunds', 'main_group' => 0, 'parent_id' => 248),
            array('name' => 'staff_listing_reports_manage', 'title' => 'Staff Listing Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'staff_listing_reports_region_wise_staff_list', 'title' => 'Region Wise Staff List', 'main_group' => 0, 'parent_id' => 255),
            array('name' => 'staff_listing_reports_centre_wise_staff_list', 'title' => 'Centre Wise Staff List', 'main_group' => 0, 'parent_id' => 255),
            array('name' => 'staff_revenue_reports_manage', 'title' => 'Staff Revenue Reports', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'staff_revenue_reports_center_performance_stats_by_revenue', 'title' => 'Staff Revenue Centre Wise', 'main_group' => 0, 'parent_id' => 258),
            array('name' => 'staff_revenue_reports_center_performance_stats_by_service_type', 'title' => 'Staff Revenue by Service Type', 'main_group' => 0, 'parent_id' => 258),
            array('name' => 'appointments_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'users_active', 'title' => 'Active', 'main_group' => 0, 'parent_id' => 27),
            array('name' => 'users_inactive', 'title' => 'Inactive', 'main_group' => 0, 'parent_id' => 27),
            array('name' => 'appointments_patient_card', 'title' => 'Patient Card', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_invoice_display', 'title' => 'Invoice Display', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'custom_forms_create_medical_history_form', 'title' => 'Create Medical History Form', 'main_group' => 0, 'parent_id' => 142),
            array('name' => 'appointments_medical_form_manage', 'title' => 'Medical History Form', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_medical_create', 'title' => 'Medical Form Create', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_medical_edit', 'title' => 'Medical Form Edit', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_plans_create', 'title' => 'Plan Create', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'pabao_records_manage', 'title' => 'Pabau Records', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'pabao_records_import', 'title' => 'Import', 'main_group' => 0, 'parent_id' => 271),
            array('name' => 'pabao_records_payment', 'title' => 'Add Payment', 'main_group' => 0, 'parent_id' => 271),
            array('name' => 'pabao_records_detail', 'title' => 'Detail', 'main_group' => 0, 'parent_id' => 271),
            array('name' => 'pabao_records_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 271),
            array('name' => 'finance_general_revenue_reports_general_revenue__detail_report', 'title' => 'General Revenue Report Detail', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_general_revenue__summary_report', 'title' => 'General Revenue Report Summary', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'leads_reports_now_show_report', 'title' => 'Now Show Report', 'main_group' => 0, 'parent_id' => 205),
            array('name' => 'finance_general_revenue_reports_pabau_record_revenue_report', 'title' => 'Pabau Record Revenue', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_machine_wise_invoice_revenue_report', 'title' => 'Machine wise Invoice Revenue Report', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_partner_collection_report', 'title' => 'Partner Collection Report', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'plans_service_delete', 'title' => 'Plan Service Delete', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'plans_cash_edit', 'title' => 'Plan Cash Edit', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'plans_cash_delete', 'title' => 'Plan Cash Delete', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'patients_plan_service_delete', 'title' => 'Patient Plan Service Delete', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_cash_edit', 'title' => 'Patient Plan Cash Edit', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_cash_delete', 'title' => 'Patient Plan Cash Delete', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'finance_general_revenue_reports_staff_wise_revenue', 'title' => 'Staff Wise Revenue', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_conversion_report', 'title' => 'Conversion Report', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'dashboard_collection_by_centre', 'title' => 'Collection by Centre', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'dashboard_my_collection_by_centre', 'title' => 'My Collection by Centre', 'main_group' => 0, 'parent_id' => 5),
            array('name' => 'appointment_reports_general_summary_report', 'title' => 'General Report Summary', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'finance_general_revenue_reports_machine_wise_collection_report', 'title' => 'Machine wise Collection Report', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'finance_general_revenue_reports_collection_by_service', 'title' => 'Collection by Service', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'centre_targets_manage', 'title' => 'Centre Targets', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'centre_targets_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 295),
            array('name' => 'centre_targets_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 295),
            array('name' => 'centre_targets_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 295),
            array('name' => 'operations_reports_center_target_report', 'title' => 'Center Target Report', 'main_group' => 0, 'parent_id' => 217),
            array('name' => 'appointments_export_today', 'title' => 'Today', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_export_this_month', 'title' => 'This Month', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_export_all', 'title' => 'All', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointment_reports_compliance_reports', 'title' => 'Compliance Report', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'appointments_log', 'title' => 'Log', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'appointments_log_excel', 'title' => 'Log Excel', 'main_group' => 0, 'parent_id' => 65),
            array('name' => 'plans_log', 'title' => 'Log', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'plans_log_excel', 'title' => 'Plans Excel Log', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'invoices_log', 'title' => 'Log', 'main_group' => 0, 'parent_id' => 165),
            array('name' => 'invoices_log_excel', 'title' => 'Excel Log', 'main_group' => 0, 'parent_id' => 165),
            array('name' => 'patients_plan_log', 'title' => 'Plan Log', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_log_excel', 'title' => 'Plan Log Excel', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_invoice_log', 'title' => 'Invoice Log', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_invoice_log_excel', 'title' => 'Invoice Log Excel', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'plans_cash_edit_payment_mode', 'title' => 'Plan Cash Edit Payment Mode', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'plans_cash_edit_amount', 'title' => 'Plan Cash Edit Amount', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'plans_cash_edit_date', 'title' => 'Plan Cash Edit Date', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'patients_plan_cash_edit_payment_mode', 'title' => 'Patient Plan Cash Edit Payment Mode', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_cash_edit_amount', 'title' => 'Patient Plan Cash Edit Amount', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_cash_edit_date', 'title' => 'Patient Plan Cash Edit Date', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'finance_general_revenue_reports_consume_plan_revenue_report', 'title' => 'Consume Plan Revenue Report', 'main_group' => 0, 'parent_id' => 239),
            array('name' => 'machineType_manage', 'title' => 'MachineType', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'machineType_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 324),
            array('name' => 'machineType_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 324),
            array('name' => 'machineType_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 324),
            array('name' => 'machineType_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 324),
            array('name' => 'finance_ledger_reports_plan_maturity', 'title' => 'Plan Maturity', 'main_group' => 0, 'parent_id' => 248),
            array('name' => 'appointment_reports_rescheduled_count_report', 'title' => 'Appointment Rescheduled Count Report', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'patients_invoice_sms_log', 'title' => 'Invoice Sms Log', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'patients_plan_sms_log', 'title' => 'Plan Sms Log', 'main_group' => 0, 'parent_id' => 169),
            array('name' => 'plans_sms_log', 'title' => 'Sms Log', 'main_group' => 0, 'parent_id' => 157),
            array('name' => 'invoices_sms_log', 'title' => 'Sms Log', 'main_group' => 0, 'parent_id' => 165),
            array('name' => 'towns_manage', 'title' => 'Towns', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'towns_create', 'title' => 'Create', 'main_group' => 0, 'parent_id' => 336),
            array('name' => 'towns_edit', 'title' => 'Edit', 'main_group' => 0, 'parent_id' => 336),
            array('name' => 'towns_active', 'title' => 'Activate', 'main_group' => 0, 'parent_id' => 336),
            array('name' => 'towns_inactive', 'title' => 'Inactivate', 'main_group' => 0, 'parent_id' => 336),
            array('name' => 'towns_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 336),
            array('name' => 'towns_import', 'title' => 'Import', 'main_group' => 0, 'parent_id' => 336),
            array('name' => 'new test patient', 'title' => 'Test', 'main_group' => 0, 'parent_id' => 295),
            array('name' => 'leads_destroy', 'title' => 'Delete', 'main_group' => 0, 'parent_id' => 92),
            array('name' => 'contact', 'title' => 'Contact', 'main_group' => 1, 'parent_id' => 0),
            array('name' => 'gfhfg', 'title' => 'gfhfh', 'main_group' => 0, 'parent_id' => 209),
            array('name' => 'fsdf', 'title' => 'df', 'main_group' => 0, 'parent_id' => 39),
        ];
    }
}
