<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Helpers\ACL;
use App\Http\Controllers\Admin\InvoicesController as AdminInvoicesController;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ResendInvoiceSMSRequest;
use App\Http\Resources\Invoice\InvoiceDetailResource;
use App\Http\Resources\Invoice\InvoiceResource;
use App\Http\Resources\Invoice\InvoiceSMSLogResource;
use App\Models\Invoices;
use App\Models\SMSLogs;
use App\Services\PatientManagement\PatientSearchService;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\ValidationException;

/**
 * Invoices REST API.
 *
 * Invoices are never created or edited directly — they're generated by
 * the appointment/package flow. This controller therefore exposes only
 * read + cancel + SMS-log operations, mirroring what the legacy admin UI
 * actually supports.
 */
class InvoicesController extends Controller
{
    public function __construct(
        private readonly AdminInvoicesController $adminController,
    ) {}

    /**
     * GET /api/invoices
     *
     * Paginated list scoped to the caller's account and the centres their
     * ACL allows (same `ACL::getUserCentres()` gate the legacy datatable
     * uses). Supports common filters — `q` is the unified search box (same
     * engine as Plans / Treatments / Consultations): it routes a `C-<id>`
     * code / phone / name to the patient via PatientSearchService, and a
     * plain number to the invoice number OR that patient's id. (`search`
     * is the older invoice-number-only param, kept for back-compat.) Pass
     * `patient_id`, `location_id`,
     * `invoice_status_id`, `invoice_status_slug`, `appointment_type_id`,
     * `created_from`, `created_to` to narrow results. `invoice_status_slug`
     * is the stable, tenant-independent way to target a status (e.g. the
     * "Cancelled" quick filter) since status ids can differ per tenant.
     *
     * Permission: `invoices.list.view`.
     */
    public function index(Request $request): JsonResponse
    {
        try {
            if (! Gate::allows('invoices.list.view')) {
                return $this->errorResponse('You are not authorized to access this resource.', 403);
            }

            $request->validate([
                'q' => ['nullable', 'string', 'max:50'],
                'search' => ['nullable', 'string', 'max:50'],
                'patient_id' => ['nullable', 'integer'],
                'location_id' => ['nullable', 'integer'],
                'service_id' => ['nullable', 'integer'],
                'invoice_status_id' => ['nullable', 'integer'],
                'invoice_status_slug' => ['nullable', 'string', 'max:50'],
                'appointment_type_id' => ['nullable', 'integer'],
                'created_from' => ['nullable', 'date'],
                'created_to' => ['nullable', 'date', 'after_or_equal:created_from'],
                'per_page' => ['nullable', 'integer', 'min:1', 'max:200'],
            ]);

            $accountId = (int) Auth::user()->account_id;

            $query = Invoices::query()
                ->with([
                    'user:id,name,phone',
                    'invoicestatus:id,name,slug',
                    'appointment:id,appointment_type_id,service_id,location_id',
                    'appointment.location:id,name',
                    'invoiceDetailService:id,invoice_id,service_id',
                    'invoiceDetailService.service:id,name',
                ])
                ->where('account_id', $accountId)
                ->whereIn('location_id', ACL::getUserCentres());

            if ($request->filled('search')) {
                $search = trim((string) $request->string('search'));
                $numeric = ltrim($search, '0');
                if ($numeric !== '' && ctype_digit($numeric)) {
                    $query->where('id', (int) $numeric);
                }
            }

            if ($request->filled('q')) {
                // Unified search box, mirroring the Plans datatable: a plain
                // number is ambiguous, so match the invoice number OR that
                // patient's id; everything else (C-<id> code / phone / name)
                // routes through the shared patient classifier. `id` IS the
                // invoice number — InvoiceResource zero-pads it via %05d.
                $q = trim((string) $request->string('q'));
                $shape = PatientSearchService::classifySearchInput($q);
                if ($shape['type'] === 'short_id') {
                    $idVal = (int) $shape['digits'];
                    $query->where(function ($inner) use ($idVal): void {
                        $inner->where('id', $idVal)
                            ->orWhere('patient_id', $idVal);
                    });
                } else {
                    PatientSearchService::applyPatientFilter($query, $q, 'patient_id', $accountId);
                }
            }

            if ($request->filled('patient_id')) {
                $query->where('patient_id', (int) $request->integer('patient_id'));
            }

            if ($request->filled('location_id')) {
                $query->where('location_id', (int) $request->integer('location_id'));
            }

            if ($request->filled('invoice_status_id')) {
                $query->where('invoice_status_id', (int) $request->integer('invoice_status_id'));
            }

            if ($request->filled('invoice_status_slug')) {
                // Slug is the stable cross-tenant key (status ids drift per
                // tenant), mirroring how CancelRecord resolves 'cancelled'.
                $slug = trim((string) $request->string('invoice_status_slug'));
                $query->whereHas('invoicestatus', fn ($q) => $q->where('slug', $slug));
            }

            if ($request->filled('appointment_type_id')) {
                $typeId = (int) $request->integer('appointment_type_id');
                $query->whereHas('appointment', fn ($q) => $q->where('appointment_type_id', $typeId));
            }

            if ($request->filled('service_id')) {
                // `service_id` lives on `invoice_details`, not `invoices`.
                // Filter via the `invoiceDetailService` HasOne relation so
                // the index stays consistent with `show`, which sources the
                // service from the same table.
                $serviceId = (int) $request->integer('service_id');
                $query->whereHas(
                    'invoiceDetailService',
                    fn ($q) => $q->where('service_id', $serviceId),
                );
            }

            if ($request->filled('created_from')) {
                $query->where('created_at', '>=', Carbon::parse($request->input('created_from'))->startOfDay());
            }

            if ($request->filled('created_to')) {
                $query->where('created_at', '<=', Carbon::parse($request->input('created_to'))->endOfDay());
            }

            $perPage = (int) ($request->integer('per_page') ?: 25);

            $paginated = $query->orderByDesc('created_at')->paginate($perPage);

            return $this->successResponse(
                'Invoices retrieved successfully.',
                [
                    'items' => InvoiceResource::collection($paginated->items()),
                    'meta' => [
                        'current_page' => $paginated->currentPage(),
                        'last_page' => $paginated->lastPage(),
                        'per_page' => $paginated->perPage(),
                        'total' => $paginated->total(),
                    ],
                ],
            );
        } catch (ValidationException $e) {
            return $this->errorResponse($e->getMessage(), 422, $e->errors());
        } catch (\Exception $e) {
            return $this->handleException($e, 'Api\\InvoicesController@index');
        }
    }

    /**
     * GET /api/invoices/{invoice}
     *
     * Full payload — invoice + invoice_details + patient / location /
     * service / status / account / doctor. Mirrors the legacy
     * `displayInvoice` response with a whitelisted JSON shape.
     */
    public function show(Invoices $invoice): JsonResponse
    {
        try {
            if (! Gate::allows('invoices.detail.view')) {
                return $this->errorResponse('You are not authorized to access this resource.', 403);
            }

            if (! $this->ownedByCaller($invoice)) {
                return $this->errorResponse('Invoice not found.', 404);
            }

            $invoice->load([
                'user',
                'invoicestatus',
                'invoiceDetailService.service',
                'appointment.doctor',
            ]);

            // `location` and `account` aren't declared relations on the
            // Invoices model, so resolve them explicitly and hand the
            // preloaded values back to the resource via setRelation() —
            // this keeps the Resource's `relationLoaded()` checks honest.
            if ($invoice->location_id) {
                // Include `city` so the SPA print route can compose the
                // "<City> · <Centre>" line in the receipt header without
                // making a second request.
                $location = \App\Models\Locations::with('city:id,name')->find($invoice->location_id);
                if ($location) {
                    $invoice->setRelation('location', $location);
                }
            }

            if ($invoice->account_id) {
                $account = \App\Models\Accounts::find($invoice->account_id);
                if ($account) {
                    $invoice->setRelation('account', $account);
                }
            }

            return $this->successResponse(
                'Invoice retrieved successfully.',
                new InvoiceDetailResource($invoice),
            );
        } catch (\Exception $e) {
            return $this->handleException($e, 'Api\\InvoicesController@show');
        }
    }

    /**
     * POST /api/invoices/{invoice}/cancel
     *
     * Cancels the invoice — reverses the till via `PackageAdvances`,
     * restores the appointment status, and logs the activity. Delegates
     * to the legacy admin controller so the business logic stays in one
     * place; a future refactor can extract the flow into a dedicated
     * `CancelInvoiceAction`.
     *
     * Gate + tenant scoping are enforced in the admin controller already,
     * but we do an up-front tenant check here too so we can return the
     * proper 404 shape from the API.
     */
    public function cancel(Invoices $invoice): JsonResponse
    {
        try {
            if (! Gate::allows('invoices.cancel')) {
                return $this->errorResponse('You are not authorized to perform this action.', 403);
            }

            if (! $this->ownedByCaller($invoice)) {
                return $this->errorResponse('Invoice not found.', 404);
            }

            return $this->adminController->cancel((int) $invoice->id);
        } catch (\Exception $e) {
            return $this->handleException($e, 'Api\\InvoicesController@cancel');
        }
    }

    /**
     * GET /api/invoices/{invoice}/sms-logs
     *
     * Returns the SMS log history for this invoice, newest first.
     *
     * Permission: `invoices.sms_log.view`.
     */
    public function smsLogs(Invoices $invoice): JsonResponse
    {
        try {
            if (! Gate::allows('invoices.sms_log.view')) {
                return $this->errorResponse('You are not authorized to access this resource.', 403);
            }

            if (! $this->ownedByCaller($invoice)) {
                return $this->errorResponse('Invoice not found.', 404);
            }

            $logs = SMSLogs::where('invoice_id', $invoice->id)
                ->orderByDesc('created_at')
                ->get();

            return $this->successResponse(
                'Invoice SMS logs retrieved successfully.',
                InvoiceSMSLogResource::collection($logs),
            );
        } catch (\Exception $e) {
            return $this->handleException($e, 'Api\\InvoicesController@smsLogs');
        }
    }

    /**
     * POST /api/invoices/{invoice}/resend-sms
     *
     * Re-sends a previously-logged SMS. Body: `{ id: <sms_log_id> }`.
     * Delegates to the legacy admin `sendLogSMS` so the Telenor/Jazz
     * operator routing stays in one place.
     */
    public function resendSMS(ResendInvoiceSMSRequest $request, Invoices $invoice): JsonResponse
    {
        try {
            if (! $this->ownedByCaller($invoice)) {
                return $this->errorResponse('Invoice not found.', 404);
            }

            $logId = (int) $request->validated()['id'];

            $log = SMSLogs::where('id', $logId)
                ->where('invoice_id', $invoice->id)
                ->first();

            if (! $log) {
                return $this->errorResponse('SMS log not found for this invoice.', 404);
            }

            $proxied = new Request(['id' => $logId]);
            $response = $this->adminController->sendLogSMS($proxied);

            $payload = $response->getData(true);
            $ok = isset($payload['status']) && (int) $payload['status'] === 1;

            return $ok
                ? $this->successResponse('SMS has been re-sent successfully.')
                : $this->errorResponse('SMS could not be re-sent. Please try again.', 502);
        } catch (ValidationException $e) {
            return $this->errorResponse($e->getMessage(), 422, $e->errors());
        } catch (\Exception $e) {
            return $this->handleException($e, 'Api\\InvoicesController@resendSMS');
        }
    }

    // ── internal helpers ──

    private function ownedByCaller(Invoices $invoice): bool
    {
        return (int) $invoice->account_id === (int) Auth::user()->account_id;
    }
}
