<div id="doctor_sales_report">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h4>Doctor Sales Report for Selected Location</h4>
        
    </div>

    <div class="alert alert-info">
        <i class="fas fa-info-circle"></i>
        <strong>Sales Report:</strong> Shows revenue generated by doctors/FDMs who <strong>sold</strong> the services (sellers).
        <br>
        <strong>Consultant Revenue:</strong> Shows revenue attributed to doctors who <strong>performed</strong> the appointments.
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Doctor (Seller)</th>
                <th>Total Sold Amount</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reportData as $report)
                <tr>
                    <td>{{ $report->doctor_name ?? 'Unknown' }}</td>
                    <td>{{ number_format($report->total_sold_amount, 2) }}</td>
                    <td>
                        <a href="{{ route('admin.doctor.upselling.detail', $report->doctor_id) }}"
                           class="btn btn-primary btn-sm mr-1">
                            <i class="fas fa-eye"></i> View Details
                        </a>
                        <a href="{{ route('admin.doctor.consultant.breakdown', $report->doctor_id) }}"
                           class="btn btn-success btn-sm">
                            <i class="fas fa-user-md"></i> Consultant Breakdown
                        </a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="3" class="text-center">No data available for this location.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</div>