<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::transaction(function (): void {
            $garbageNames = ['gfhfg', 'fsdf', 'new test patient'];

            $garbageIds = DB::table('permissions')
                ->whereIn('name', $garbageNames)
                ->pluck('id')
                ->all();

            if (!empty($garbageIds)) {
                DB::table('role_has_permissions')
                    ->whereIn('permission_id', $garbageIds)
                    ->delete();

                DB::table('permissions')
                    ->whereIn('id', $garbageIds)
                    ->delete();
            }

            $businessClosuresParentId = DB::table('permissions')
                ->where('name', 'business_closures_manage')
                ->where('main_group', 1)
                ->value('id');

            if ($businessClosuresParentId) {
                DB::table('permissions')
                    ->whereIn('name', [
                        'business_closures_create',
                        'business_closures_edit',
                        'business_closures_delete',
                    ])
                    ->where('parent_id', 0)
                    ->update(['parent_id' => $businessClosuresParentId]);
            }

            DB::table('permissions')
                ->where('name', 'regions_sort')
                ->where('title', 'Delete')
                ->update(['title' => 'Sort']);

            $titleRepairs = [
                'appointment_reports_clients_by_appointment_status' => 'Patient by Appointment Status (Weekly)',
                'operations_reports_List_of_refunds_for_a_certain_period_date_based' => 'List of refunds for a certain period (date based)',
                'Hr_reports_revenue_generated_by_operators_application_user' => 'Revenue Generated By Operators (Application User)',
                'Hr_reports_revenue_generated_by_consultants_practitioner' => 'Revenue Generated By Consultants (Practitioner)',
            ];

            foreach ($titleRepairs as $name => $correctTitle) {
                DB::table('permissions')
                    ->where('name', $name)
                    ->where('title', '!=', $correctTitle)
                    ->update(['title' => $correctTitle]);
            }
        });
    }

    public function down(): void
    {
        // No-op: data repair is restored via the pre-migration mariadb-dump in
        // storage/backups/permissions_pre_recat_*.sql if rollback is required.
    }
};
