<?php

/**
 * Dumps the schema (CREATE TABLE statements only — no data) of the local
 * `crm` database into `mariadb_testing-schema.sql`. This file is loaded by
 * Laravel's `schema:load` mechanism (see `config/database.php` mariadb_testing
 * connection) so the test database can be hydrated from a curated schema
 * snapshot rather than running 275 historical migrations — many of which
 * assume production-DB state and cannot apply cleanly on a fresh DB.
 *
 * To regenerate (only when the dev `crm` schema changes):
 *
 *     php database/schema/dump_schema.php
 *
 * The output is checked into the repo so CI does not depend on a local
 * MariaDB instance.
 *
 * Note: the `mysql:` PDO DSN prefix below is a PHP language identifier
 * (from the `pdo_mysql` extension, which is the only PHP driver for MariaDB).
 * It is not removable and not a project-level MySQL reference.
 */

$host = '127.0.0.1';
$port = (int) (getenv('SCHEMA_DUMP_PORT') ?: 3306);
$user = 'root';
$pass = '';
$db = 'crm';

$pdo = new PDO("mysql:host={$host};port={$port};dbname={$db}", $user, $pass, [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);

$tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);

$lines = [];
$lines[] = '-- Auto-generated by database/schema/dump_schema.php';
$lines[] = '-- DO NOT EDIT BY HAND — regenerate via: php database/schema/dump_schema.php';
$lines[] = '-- Source: local `crm` database (production-like schema)';
$lines[] = '';
$lines[] = 'SET FOREIGN_KEY_CHECKS=0;';
$lines[] = 'SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";';
$lines[] = '';

foreach ($tables as $table) {
    $row = $pdo->query("SHOW CREATE TABLE `{$table}`")->fetch(PDO::FETCH_ASSOC);
    $createSql = $row['Create Table'] ?? null;

    if ($createSql === null) {
        // VIEW or other object — skip
        continue;
    }

    // Strip AUTO_INCREMENT=N suffixes so the dump is reproducible regardless
    // of how many rows the source DB has accumulated.
    $createSql = preg_replace('/\s+AUTO_INCREMENT=\d+/', '', $createSql);

    $lines[] = "DROP TABLE IF EXISTS `{$table}`;";
    $lines[] = $createSql . ';';
    $lines[] = '';
}

// Re-enable FK checks at the end so the loaded session is in a sane state.
$lines[] = 'SET FOREIGN_KEY_CHECKS=1;';
$lines[] = '';

$out = implode("\n", $lines);
$path = __DIR__ . '/mariadb_testing-schema.sql';
file_put_contents($path, $out);

echo "Wrote " . count($tables) . " tables to {$path}\n";
echo "File size: " . number_format(filesize($path)) . " bytes\n";
